
variables:

stages:
  - Build

before_script:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd"

windows-build:
  stage: Build
  only:
    - features
  script:
  - perl mkfiles.pl
  - "echo #define SOURCE_COMMIT \"%CI_COMMIT_SHA%\" > version.h"
  - "echo #define BINARY_VERSION 0,72,0,0 >> version.h"
  - "echo #define TEXTVER \"PuTTY Release 0.72 (%CI_COMMIT_REF_NAME% branch)\" >> version.h"
  - "echo #define SSHVER \"-Unidentified-Local-Build\" >> version.h"
  - cd windows
  - nmake -f Makefile.vc BUILD=release
  - signtool sign /v /f C:\GitLab-Runner\private\putty-leoleung-spc.pfx /fd sha256 /tr http://sha256timestamp.ws.symantec.com/sha256/timestamp /td sha256 putty.exe
  artifacts:
    paths:
      - windows/putty.exe
    expire_in: 1 week

