
variables:

stages:
  - Build

before_script:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd"

windows-build:
  stage: Build
  only:
    - features
  script:
  - perl mkfiles.pl
  - "echo #define SOURCE_COMMIT \"%CI_COMMIT_SHA%\" > version.h"
  - "echo #define BINARY_VERSION 0,71,0,0 >> version.h"
  - "echo #define TEXTVER \"PuTTY Release 0.71 (%CI_COMMIT_REF_NAME% branch)\" >> version.h"
  - "echo #define SSHVER \"-Unidentified-Local-Build\" >> version.h"
  - cd windows
  - nmake Makefile.vc
  - signtool sign /v /f C:\GitLab-Runner\private\putty-leoleung-spc.pfx /t http://timestamp.verisign.com/scripts/timstamp.dll windows\putty.exe
  artifacts:
    paths:
      - windows/putty.exe
    expire_in: 1 week

